### ISSUE TITLE
Hit point updates aren't reliable with big seeks forward, or with any backward seeking

### ISSUE THREAD

**Issue by pcordes** [snappdragonn/CritRoleHpTracker#10] opened 2024-02-23 08:27 UTC
FCG's hit points seem glitchy when seeking around during the final Otohan encounter in C3E85.  When they're showing as 16 afterwards, seeking back to before the attacks leaves them as 16.  (With the mouse on the slider bar, or holding down J with auto-repeat.)

But another time, seeking forward past the attacks left them as near-full.  (Refreshing the page with F5 or after an ad seems to restore the HP to what it should be.)  This time, seeking with the mouse in big skips vs. small skips did seem to make a difference.  If you can't reproduce, I can play around some more and report some more specific details of steps.

I didn't check on spell slots or status effects updating correctly, just what can be seen without hovering.

**Comment by snappdragonn** [comment] 2024-03-06 07:50
I found an error with the first combat (when they opened the portable hole) caused by a spelling mistake which I've fixed now. I think that was probably what was causing the problems with FCG's hp later on and as far as I can tell it looks like it's fixed now.

**Closed as completed** 2024-04-08 05:09 UTC
